#!/usr/bin/env node
// Bundles src/*.js + packs/*.json into single-file dist artifacts.
// No deps, no minifier, no eval — pack JSON is valid JS object-literal syntax already.
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const ROOT = __dirname;
const SRC_DIR = path.join(ROOT, 'src');
const PACKS_DIR = path.join(ROOT, 'packs');
const DIST_DIR = path.join(ROOT, 'dist');

// core.js first: canary.js reads window.driftwatch / requires('./core.js') at load time.
const srcFiles = fs.readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.js'))
  .sort((a, b) => (a === 'core.js' ? -1 : b === 'core.js' ? 1 : a.localeCompare(b)));

const packs = {};
for (const f of fs.readdirSync(PACKS_DIR).filter((f) => f.endsWith('.json'))) {
  packs[path.basename(f, '.json')] = JSON.parse(fs.readFileSync(path.join(PACKS_DIR, f), 'utf8'));
}

const body = srcFiles.map((f) => fs.readFileSync(path.join(SRC_DIR, f), 'utf8')).join('\n');

const registerPacks = `
(function (root) {
  var packs = ${JSON.stringify(packs, null, 2)};
  if (root) { root.driftwatch = root.driftwatch || {}; root.driftwatch.packs = packs; }
  if (typeof module !== 'undefined' && module.exports) module.exports.packs = packs;
})(typeof window !== 'undefined' ? window : (typeof globalThis !== 'undefined' ? globalThis : this));
`;

const bundle = '// Generated by build.js — do not edit directly.\n'
  + '(function () {\n' + body + '\n' + registerPacks + '\n})();\n';

fs.mkdirSync(DIST_DIR, { recursive: true });
fs.writeFileSync(path.join(DIST_DIR, 'driftwatch.js'), bundle);
fs.writeFileSync(path.join(DIST_DIR, 'driftwatch.cjs'), bundle);
console.log('wrote dist/driftwatch.js and dist/driftwatch.cjs (' + bundle.length + ' bytes)');
